version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${PORT:-3000} -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
